language: node_js
node_js:
   - "0.11"
   - "0.10"
after_success:
   - COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=v3Z17MGbBBtEfe6sA6xNbWkG0OYxNtDyx node_modules/.bin/alinex-make -c test --coverage --coveralls