# Email Template
# =================================================

default:
  from: monitor
  subject: >
    {{alias}} => {{status}}
  body: |+
    {{name}}
    ==========================================================================
    {{description}}

    This test failed at {{date}}!

    {{hint}}
