# Defaults for Monitoring
# =================================================
# This file holds a list of contacts to be used from within the rules and
# specific controllers.

# System Contact
# -------------------------------------------------
contact:
  monitor:
    name: Alinex Monitor
    email: monitor@<<<cmd://hostname#1 | localhost>>>

# Email Template
# -------------------------------------------------
email:
  default:
    from: monitor
    subject: >
      {{alias}} => {{status}}
    body: >
      {{name}}\n
      ==========================================================================\n
      {{description}}\n
      \n
      This test failed at {{date}}!\n
      \n
      {{hint}}\n

# Rule Template
# -------------------------------------------------

rule:

  fail:
    name: fail
    status: fail
    attempt: 3
    latency: 60
    dependskip: true
    email:
      base: default
    redo: 3h

  warn:
    name: warn
    status: warn
    attempt: 3
    latency: 60
    dependskip: true
    email:
      base: default
    redo: 3h

  ok:
    name: ok
    status: ok
    email:
      base: default

# When to cleanup entries from storage
# -------------------------------------------------
# The values are the number of max. entries of given interval.
storage:
  cleanup:
    minute: 360 # 6 hours
    hour: 96 # 4 days
    day: 90 # 3 months
    week: 104 # two years
    month: 60 # 5 years
    other: 2160 # 5years
