# Contacts for Monitoring
# =================================================
# This file holds a list of contacts to be used from within the rules and
# specific controllers.

# Groups
# -------------------------------------------------
operations: [aschi, malbr, yzhao]

# Staff
# -------------------------------------------------
aschi:
  name: Alexander Schilling
  position: IT Operations
  company: divibib GmbH
  email: alexander.schilling@4readers.org
  phone: 07129/922545

malbr:
  name: Michael Albrecht
  position: IT Operations
  company: divibib GmbH
  email: michael.albrecht@divibib.com

yzhao:
  name: Yingli Zhao
  position: IT Operations
  company: divibib GmbH
  email: yingli.zhao@divibib.com

