# Email Report Configuration
# =================================================

email:

  default:
    subject: $alias => $status
    body: |
      {{name}}
      =========================================================
      \
      {{description}}
      \
      This test had status $status at {{date}}!
      \
      {{hint}}

  fail:
    subject: Failed $alias
    body: |
      <h1>$name</h1>
      <p>$description</p>
      <p><b>This test failed at $date!</b></p>
      <p>$hint</p>

  warn:
    subject: Warning for $alias
    body: |
      <h1>$name</h1>
      <p>$description</p>
      <p><b>This test has warn state since $date!</b></p>
      <p>$hint</p>

  ok:
    subject: OK for $alias
    body: |
      <h1>$name</h1>
      <p>$description</p>
      <p><b>This test succeeds again since $date!</b></p>
      <p>$hint</p>

