# Email Report Configuration
# =================================================

transport:
  # the port to connect to (defaults to 25 or 465)
  #port:
  # the hostname or IP address to connect to (defaults to 'localhost')
  #host:
  # defines if the connection should use SSL (if true) or not (if false)
  #secure:
  # defines authentication data (see authentication section below)
  #auth:
  #  user:
  #  pass:
  # turns off STARTTLS support if true
  #ignoreTLS:
  # optional hostname of the client, used for identifying to the server
  #name:
  # is the local interface to bind to for network connections
  #localAddress:
  # how many milliseconds to wait for the connection to establish
  #connectionTimeout:
  # how many milliseconds to wait for the greeting after connection is established
  #greetingTimeout:
  # how many milliseconds of inactivity to allow
  #socketTimeout:
  # defines preferred authentication method, eg. 'PLAIN'
  #authMethod:


# Default (extended)
# -------------------------------------------------

default:
  # already defined, so only set the 'To' address here.
  to: operations

# Own Templates
# -------------------------------------------------

fail:
  subject: >
    Failed {{alias}}
  body: >
    {{name}}\n
    ==========================================================================\n
    {{description}}\n
    \n
    This test failed at {{date}}!\n
    \n
    {{hint}}\n

warn:
  subject: >
    Warning for {{alias}}
  body: >
    {{name}}\n
    ==========================================================================\n
    {{description}}\n
    \n
    This test failed at {{date}}!\n
    \n
    {{hint}}\n

ok:
  subject: >
    OK for {{alias}}
  body: >
    {{name}}\n
    ==========================================================================\n
    {{description}}\n
    \n
    This test failed at {{date}}!\n
    \n
    {{hint}}\n

