# Rule Templates
# =================================================

# ### Set templates for default rules
fail:
  email:
    base: fail

warn:
  email:
    base: warn

ok:
  email:
    base: ok

# ### specific check
specific:
  # Only work on specific status.
  status: fail
  # Number of minimum attempts before informing.
  attempt: 3
  # Time (in seconds) to wait before informing.
  latency: 60
  # Only inform if dependent jobs not failed. This prevents of hundred of
  # messages if a central system failed.
  dependskip: true
  # Type of actor to run with it's configuration
  email:
    base: fail # template to use defined under monitor/email
  # Timeout (in seconds) without status change before informing again.
  redo: 3h
